### ISSUE TITLE
[ BUG ] Breaking changes introduced in (at least) falconpy.oauth2.OAuth2 class

### ISSUE THREAD

**Issue by morcef** [CrowdStrike/falconpy#1043]
**Describe the bug**
After upgrading to falconpy 1.3.1, I noticed a breaking change in the OAuth2 class. Previously both OAuth2.token_expired and OAuth2.authenticated were lambda functions (called as class methods), while they now are set as properties.

**To Reproduce**
Install falconpy < 1.3.0 and this code runs fine:
```
from falconpy import OAuth2

auth_object = OAuth2(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
)
auth_object.token()
auth_object.authenticated()
```
Then install falconpy >= 1.3.0, and this will return:
```
TypeError: 'bool' object is not callable
```

**Expected behavior**
Since this is not a major version update, this breaking change should not have been introduced.

**Additional context**
I have not look back into the history to verify if any other lambda functions were used previously elsewhere.

**Comment by jshcodes** [comment]
This is a _fantastic_ catch that should have been identified in acceptance testing!

The good news is, I'm pretty sure this will only effect the `OAuth2` service class, and should be an easy fix. The `authenticated` method is deprecated, this is [handled within the `ServiceClass` interface class](https://github.com/CrowdStrike/falconpy/blob/main/src/falconpy/_service_class/_service_class.py#L187). 

Since `OAuth2` uses `FalconInterface` as a base class instead of `ServiceClass`, it's not inheriting this method. We should be able to address this by adding a deprecated handler from this method to the `OAuth2` class.

I'm testing this change now, thank you for reporting the issue!!

**Comment by jshcodes** [comment]
Figured this out I believe and am running a full unit test series now.  Will also check for other potential legacy handlers like this that may have been missed by the `OAuth2` refactor.

This fix will release individually sometime this week as version `1.3.2`. 😃

**Comment by jshcodes** [comment]
Hi @morcef!

Unfortunately, due to architectural constraints, resolving this was not as easy as I was hoping. We do have a resolution undergoing testing now, but there are a few changes that I need to detail.

### A little background
In versions prior to `1.3.0`, `authenticated` was defined as an attribute within the Uber Class. In regular Service Classes, this was defined as a callable method. In the special Service Class, __OAuth2__ (i.e. the legacy Authentication Object), this was defined as an attribute (which was a callable lambda).

One of the goals of the `1.3.0` refactor was to clean up a lot of this technical debt, align the terms used for specific functionality, and leverage shared objects where possible (and where it made sense). Due to all the naming collisions, `authenticated` was pretty high up on the list of targets to get refactored. It appears we successfully addressed every variation of potential conflict with this attribute's changes ... _except_ for this scenario.  (Insert booing crowd noises here.) This is an older usage pattern, and does not affect developers making use of regular Service Classes while leveraging Direct, Object, Credential, Environment or Object Authentication.

### Resolution
To address this breaking change and maintain backwards compatibility, we are reverting a few of the changes implemented by `1.3.0`. We are also expanding the __Uber Class__ into a submodule, which allows us to provide multiple versions of the __APIHarness__ class.

- The `authenticated` property has been renamed to be `token_valid` within the __FalconInterface__ object.
- The `token_expired` property has been renamed to be `token_stale` within the __FalconInterface__ object.
- The `authenticated` and `token_expired` abstract properties have been removed from the __BaseFalconInterface__ class.
- The `authenticated` and `token_expired` methods have been added back to regular Service Class and the special Service Class __OAuth2__.
- The Uber Class has been expanded to a submodule that provides two classes:
    + __APIHarness__ - The original Uber Class, modified to handle new constructor keywords and class properties. This modified version of the legacy Uber Class does support [Debug Logging](https://www.falconpy.io/Usage/Logging.html).  [Pythonic responses](https://www.falconpy.io/Usage/Response-Handling.html#pythonic-responses) are also implemented but this functionality should be considered extremely experimental when using the legacy version. This version of the Uber Class __*does not*__ support [Environment Authentication](https://www.falconpy.io/Usage/Authenticating-to-the-API.html#environment-authentication). This class does not inherit from __FalconInterface__, so it leverages old attributes and methods.
    + __APIHarnessV2__ - The new and improved Uber Class! Providing all functional benefits implemented within version `1.3.0`. This new version _does_ inherit from the __FalconInterface__ class, and leverages all of the new properties and derivative classes as before.

### What happens next
These changes are undergoing several rounds of unit testing, and another full round of acceptance testing where we confirm updates do not impact existing integrations or code samples. There is currently an open Pull Request (feel free to review), that will not merge to `main` until this testing has completed. 

> A pre-release package has been published to PyPI ([`1.3.2.dev1`](https://pypi.org/project/crowdstrike-falconpy/1.3.2.dev1/)) if you are interested in testing these changes locally.

Once merged, this ticket will automatically close. These changes will release to the production `1.3.2` package shortly thereafter (we will have a shortened [soak period](https://github.com/CrowdStrike/falconpy/blob/dev/docs/PACKAGING.md#falconpy-package-release-cycle) for this specific release). Finally, all documentation will be updated to reflect these changes.

We appreciate you identifying and reporting this issue for us. If you happen to be coming to Fal.Con this year, come find us on the expo hall floor. This find has definitely earned you some swag...

**Comment by morcef** [comment]
Hi @jshcodes !
Thank you for investigating this!
I had a quick look into the PR, which looks good 👍 
Unfortunately I'm not able to come back to Fal.Con this year, but hopefully sometime again soon!

**Comment by davidt99** [comment]
Not sure if this was fixed in 1.3.2, but when I pass `OAuth2` object as `auth_object` to any Uber Class, I'm receiving the following error:
```
main.py:8:
    falconpy.Detects(auth_object=self._auth_object)
/usr/local/lib/python3.11/site-packages/falconpy/_service_class/_service_class.py:166: in __init__
    if not self.token_status:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <falconpy.detects.Detects object at 0x7f8e8280a390>

    @property
    def token_status(self) -> int:
        """Provide the current token_status."""
>       return self.auth_object.token_status
E       AttributeError: 'Detects' object has no attribute 'auth_object'

/usr/local/lib/python3.11/site-packages/falconpy/_service_class/_base_service_class.py:193: AttributeError
```

**Comment by jshcodes** [comment]
> Not sure if this was fixed in 1.3.2, but when I pass `OAuth2` object as `auth_object` to any Uber Class, I'm receiving the following error:
> 
> ```
> main.py:8:
>     falconpy.Detects(auth_object=self._auth_object)
> /usr/local/lib/python3.11/site-packages/falconpy/_service_class/_service_class.py:166: in __init__
>     if not self.token_status:
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = <falconpy.detects.Detects object at 0x7f8e8280a390>
> 
>     @property
>     def token_status(self) -> int:
>         """Provide the current token_status."""
> >       return self.auth_object.token_status
> E       AttributeError: 'Detects' object has no attribute 'auth_object'
> 
> /usr/local/lib/python3.11/site-packages/falconpy/_service_class/_base_service_class.py:193: AttributeError
> ```

Hi @davidt99 -

The Uber Class does not supported Object Authentication. (In `1.3.0` it can be used as an authentication object, but it has never accepted the `auth_object` keyword.)

Can we see an example of the code being executed?  The error above looks like it's originating from the Detects Service Class, not the Uber.

**Comment by davidt99** [comment]
Sorry, my mistake, I meant service class.

**Comment by jshcodes** [comment]
Hi @davidt99 - Can we see the executed code that generated this error?

**Comment by davidt99** [comment]
This code is done in a test suite where I mock the `OAuth2` object.
So something similar to:
```
auth_object: falconpy.OAuth2 | MagicMock = MagicMock(spec=falconpy.OAuth2(), autospec=True)
detects = falconpy.Detects(auth_object=auth_object)
```

But I see that in [`_base_service_class:L67`](https://github.com/CrowdStrike/falconpy/blob/main/src/falconpy/_service_class/_base_service_class.py#L67), the type check is done by `issubclass(type(auth_object), FalconInterface)` and not `isinstance(auth_object, FalconInterface)` which autospec handles properly. I would be happy if the check would change (I can open a PR if needed).
Besides that, I also faced the `authenticated` method issue.

**Comment by jshcodes** [comment]
Copy that.  Testing this change now! 🙇

**Comment by jshcodes** [comment]
Hi @davidt99 -

You were right! Thank you for your reporting this! 🙇 

This was a quick fix and has cleared testing. We're including this update as part of the `1.3.2` release.

This is now your _second_ really cool contribution... definitely come see us if you're coming to Fal.Con this year, we'll be on the expo hall floor with your swag! 😄
