### ISSUE TITLE
[ENH] download_sensor.py / ability to choose base_url

### ISSUE THREAD

**Issue by nesies** [CrowdStrike/falconpy#1187]
**Describe the bug**
the script do not allow to choose the base_url.
The default is US1  https://api.crowdstrike.com

**To Reproduce**

**Expected behavior**
be able to choose the api
```
US1   https://api.crowdstrike.com
US2   https://api.us-2.crowdstrike.com
EU1    https://api.eu-1.crowdstrike.com
USGOV1	https://api.laggar.gcw.crowdstrike.com
```

**Comment by jshcodes** [comment]
Hello @nesies - Is this a GovCloud scenario? Base URL selection should not be required for commercial cloud customers using [FalconPy v0.8.6+](https://github.com/CrowdStrike/falconpy/releases/tag/v0.8.6) due to [Cloud Region Autodiscovery](https://falconpy.io/Usage/Environment-Configuration.html#cloud-region-autodiscovery).

Are you receiving an error related to the Base URL when executing this sample?

**Comment by ACh0wdhury** [comment]
We've ran into similar issue & was able to resolve it by updating the base_url (line 75) in _legacy.py file located under \lib\site-package\falconpy\api_complete

Looking at the falconpy documentation looks like there are other ways to update the url: https://www.falconpy.io/Usage/Environment-Configuration.html

You can try out the steps in that article as well.

**Comment by jshcodes** [comment]
Base URL selection is now supported using the `-b` command line argument.

Thank you for the report! 😄
