### ISSUE TITLE
[ BUG ] QueryDevicesByFilter Offset response

### ISSUE THREAD

**Issue by cozadk** [CrowdStrike/falconpy#305]
Using the service class to call the 'QueryDevicesByFilter' function recently (within the last day or so) started returning an offset pointer similar to the 'QueryDevicesByFilterScroll' function rather than an integer value.  The uber class seems to be working as expected.

**To Reproduce**
call `falcon.QueryDevicesByFilter` from Service Class

**Expected behavior**
Expecting an offset value as an integer in the pagination section of the response

**Environment (please complete the following information):**
 - OS: macOS 11.5.2
 - Python 3.9.6

**Additional context**
Calling the same function from the uber class returns an integer value as expected.
`falcon.command('QueryDevicesByFilter')`

**Comment by jshcodes** [comment]
Hi @cozadk!

Can you let us know which version of FalconPy you're on? (We would like to recreate and confirm this.)

**Comment by cozadk** [comment]
sry about that, was on 0.5.6 when I first noticed and downgraded to 0.5.5 and see it there as well

**Comment by jshcodes** [comment]
Copy that.  Looking into this now.

Thank you!

**Comment by cozadk** [comment]
just edited my initial post as I pasted the wrong function.  should be `falcon.QueryDevicesByFilter`

**Comment by jshcodes** [comment]
Hi @cozadk!

This issue is being caused by an error in process_service_request. 

https://github.com/CrowdStrike/falconpy/blob/main/src/falconpy/_util.py#L377 

On line 377 of _util, we are doing an "in" comparison as opposed to an "==" when looking for the operation ID within the _endpoint module. This is a bug. When you are making the call to the service class, it's matching on QueryDevicesByFilterScroll first, and returning the wrong endpoint.

We will get a fix posted for this and deployed to the current bleeding-edge version. (Bumping the version to 0.6.1) This way, the fix will roll out with the Tuesday release.

Thank you for identifying this! 😃

**Comment by cozadk** [comment]
sounds good.  Glad you were able to confirm and I appreciate the quick response!
