### ISSUE TITLE
Why can't I run a query on a limit greater than 5000 (intel ioc) ?

### ISSUE THREAD

**Issue by NSH531** [CrowdStrike/falconpy#625]
### Discussed in https://github.com/CrowdStrike/falconpy/discussions/624

<div type='discussions-op-text'>

<sup>Originally posted by **NSH531** April 26, 2022</sup>
To circumvent this limitation I have to run a script that runs at a time on 5000 indicators.
</div>
<div>
what's I can to do?
netanel
</div>

**Comment by jshcodes** [comment]
Hi @NSH531!

This limitation is maintained by the API endpoint, and not FalconPy, hence this is not a bug. 

You're correct that you will need to loop and process indicators in batches due to this limitation. 

We will have an example posted online shortly that specifically demonstrates how to iterate Intel indicators.  Expect this by the end of the month. :smile:
